"""
MITCalc Web App - Roller Chain Bundle Packager
Concatenates and bundles ChainData, ChainCalc, ChainCanvas, ChainDxf, ChainUI
into a single standalone classic JavaScript file: chain-engine.bundle.js
"""

import os, re

def bundle_chain():
    js_dir = os.path.abspath('modules/roller-chain/js')
    out_file = os.path.join(js_dir, 'chain-engine.bundle.js')

    # Read files in dependency order
    files = [
        'chain-data.js',
        'chain-calc.js',
        'chain-canvas.js',
        'chain-dxf.js',
        'chain-ui.js'
    ]

    bundle_parts = [
        '/**',
        ' * MITCalc Roller Chain Engine Bundle',
        ' * 100% Offline, Zero-CORS, Standalone Classic Script',
        ' * Auto-generated by tools/bundle_chain.py',
        ' */\n',
        '(function() {\n',
        '  "use strict";\n'
    ]

    for fname in files:
        fpath = os.path.join(js_dir, fname)
        if not os.path.exists(fpath):
            print(f'Error: {fpath} does not exist!')
            return False

        with open(fpath, 'r', encoding='utf-8') as f:
            code = f.read()

        # Strip ES6 imports and exports
        code = re.sub(r'import\s+.*?from\s+[\'"].*?[\'"];?', '', code)
        code = re.sub(r'export\s+(const|class|function|let|var)\s+', r'\1 ', code)
        code = re.sub(r'export\s*\{[^}]*\};?', '', code)

        bundle_parts.append(f'\n/* === File: {fname} === */\n')
        bundle_parts.append(code)

    bundle_parts.append('\n  if (typeof window !== "undefined") {')
    bundle_parts.append('    window.ChainData = typeof ChainData !== "undefined" ? ChainData : {};')
    bundle_parts.append('    window.ChainCalc = typeof ChainCalc !== "undefined" ? ChainCalc : {};')
    bundle_parts.append('    window.ChainCanvas = typeof ChainCanvas !== "undefined" ? ChainCanvas : {};')
    bundle_parts.append('    window.ChainDxf = typeof ChainDxf !== "undefined" ? ChainDxf : {};')
    bundle_parts.append('  }')
    bundle_parts.append('\n})();\n')

    full_bundle = '\n'.join(bundle_parts)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(full_bundle)

    size_kb = os.path.getsize(out_file) / 1024
    print(f'Successfully bundled Roller Chain engine -> {out_file} ({size_kb:.1f} KB)')
    return True

if __name__ == '__main__':
    bundle_chain()
