"""
BUNDLE GENERATOR FOR MODULE 8: KEYS & STRAIGHT-SIDED SPLINES
Packages all scripts into a single CORS-free classic script bundle:
modules/shaft-keys/js/keys-engine.bundle.js
"""

import os

files_to_bundle = [
    'modules/shaft-keys/js/keys-data.js',
    'modules/shaft-keys/js/keys-calc.js',
    'modules/shaft-keys/js/keys-canvas.js',
    'modules/shaft-keys/js/keys-dxf.js',
    'modules/shaft-keys/js/keys-ui.js',
]

bundle_path = 'modules/shaft-keys/js/keys-engine.bundle.js'

print(f"Bundling {len(files_to_bundle)} files into {bundle_path}...")

bundle_content = """/**
 * MITCalc Web App - Module 8: Keys & Straight-Sided Splines
 * 100% Offline Single Bundle (Zero-CORS, file:/// compatible)
 * Auto-generated by tools/bundle_shaft_keys.py
 */

"""

for fpath in files_to_bundle:
    if os.path.exists(fpath):
        print(f"  + Adding {fpath}")
        with open(fpath, 'r', encoding='utf-8') as f:
            bundle_content += f"\n/* --- SOURCE: {os.path.basename(fpath)} --- */\n"
            bundle_content += f.read() + "\n"
    else:
        print(f"  ! ERROR: File not found: {fpath}")

with open(bundle_path, 'w', encoding='utf-8') as f:
    f.write(bundle_content)

print(f"SUCCESS: Bundle generated: {bundle_path} ({len(bundle_content):,} bytes)")
