"""
MITCalc Web App - Involute Splines Bundle Packager
Concatenates and bundles SplinesData, SplinesCalc, SplinesCanvas, SplinesDxf, SplinesUI
into a single standalone classic JavaScript file: splines-engine.bundle.js
"""

import os, re

def bundle_splines():
    js_dir = os.path.abspath('modules/involute-splines/js')
    out_file = os.path.join(js_dir, 'splines-engine.bundle.js')

    # Read files in dependency order
    files = [
        'splines-data.js',
        'splines-calc.js',
        'splines-canvas.js',
        'splines-dxf.js',
        'splines-ui.js'
    ]

    bundle_parts = [
        '/**',
        ' * MITCalc Involute Splines Engine Bundle',
        ' * 100% Offline, Zero-CORS, Standalone Classic Script',
        ' * Auto-generated by tools/bundle_splines.py',
        ' */\n',
        '(function() {\n',
        '  "use strict";\n'
    ]

    for fname in files:
        fpath = os.path.join(js_dir, fname)
        if not os.path.exists(fpath):
            print(f'Error: {fpath} does not exist!')
            return False

        with open(fpath, 'r', encoding='utf-8') as f:
            code = f.read()

        # Strip ES6 imports and exports
        code = re.sub(r'import\s+.*?from\s+[\'"].*?[\'"];?', '', code)
        code = re.sub(r'export\s+(const|class|function|let|var)\s+', r'\1 ', code)
        code = re.sub(r'export\s*\{[^}]*\};?', '', code)

        bundle_parts.append(f'\n/* === File: {fname} === */\n')
        bundle_parts.append(code)

    bundle_parts.append('\n  if (typeof window !== "undefined") {')
    bundle_parts.append('    window.SplinesData = SplinesData;')
    bundle_parts.append('    window.SplinesCalc = SplinesCalc;')
    bundle_parts.append('    window.SplinesCanvas = SplinesCanvas;')
    bundle_parts.append('    window.SplinesDxf = SplinesDxf;')
    bundle_parts.append('    window.SplinesUI = SplinesUI;')
    bundle_parts.append('  }')
    bundle_parts.append('\n})();\n')

    full_bundle = '\n'.join(bundle_parts)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(full_bundle)

    size_kb = round(os.path.getsize(out_file) / 1024, 1)
    print(f'Successfully bundled {out_file} ({size_kb} KB)!')
    return True

if __name__ == '__main__':
    bundle_splines()
